[app]
PageSize = 10
JwtSecret = test_secret_key_for_testing_12345678
JwtExpire = 720
PrefixUrl = http://localhost:8000

RuntimeRootPath = runtime/

ImageSavePath = uploads/images/
ImageMaxSize = 2048
ImageAllowExts = .jpg,.jpeg,.png

LogSavePath = logs/
LogSaveName = test_log
LogFileExt = log
TimeFormat = 20060102

[server]
#debug or release
RunMode = debug
HttpPort = 8001
ReadTimeout = 60
WriteTimeout = 60

[database]
Type = mysql
User = test_user
Password = test_password
Host = localhost:3306
Name = test_db
TablePrefix = test_

[admin]
Username = admin
PasswordHash = $2a$10$DNblWL.KBv/DALuWq7Ac5OmNv2yWEAQm0s9kdlZz1SnHixipyw3CW
