// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "TO IMPLEMENT",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/archiveMenuItem": {
            "put": {
                "description": "设置菜品 archive 状态。下架今日推荐菜品时会自动取消今日推荐。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "下架或重新上架菜品",
                "parameters": [
                    {
                        "description": "下架参数",
                        "name": "archive",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ArchiveMenuRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/admin/comment/delete": {
            "delete": {
                "description": "管理员删除评论仅清空评论内容，不影响用户点赞状态。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "管理员删除评论",
                "parameters": [
                    {
                        "description": "删除参数",
                        "name": "delete",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DeleteCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/admin/comment/list": {
            "post": {
                "description": "管理员评论列表，可按评论内容、用户 ID、菜品名称或 ID 搜索。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "管理员获取评论列表",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AdminCommentListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.AdminCommentItem"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/admin/deleteMenuItem": {
            "delete": {
                "description": "根据菜品ID删除菜品（软删除，将状态标记为0）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "删除菜品",
                "parameters": [
                    {
                        "description": "删除参数",
                        "name": "delete",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DeleteMenuRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"invalid params\",\"data\":\"Invalid menu ID\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "{\"code\":404,\"msg\":\"not found\",\"data\":\"Menu item not found\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"internal server error\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/admin/login": {
            "post": {
                "description": "使用配置文件中的管理员账号登录，返回管理员JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "管理员登录",
                "parameters": [
                    {
                        "description": "管理员登录参数",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AdminLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{\"token\":\"...\",\"username\":\"admin\",\"role\":\"admin\"}}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"请求参数错误\",\"data\":\"Username and password are required\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "{\"code\":20004,\"msg\":\"Token错误\",\"data\":\"Invalid username or password\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/admin/menu/list": {
            "post": {
                "description": "管理员菜单列表，可查看上架中和已下架菜品。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "管理员获取菜单列表",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AdminMenuListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.MenuWithLikes"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/admin/ops/access-logs": {
            "get": {
                "description": "只读读取配置指定的 Nginx access log。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AdminOps"
                ],
                "summary": "管理员获取 Nginx 访问日志",
                "parameters": [
                    {
                        "type": "string",
                        "description": "日期，格式 YYYY-MM-DD",
                        "name": "date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最大返回条数，最多 500",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.OpsAccessLogResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/admin/ops/app-logs": {
            "get": {
                "description": "只读读取配置指定的后端应用日志目录。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AdminOps"
                ],
                "summary": "管理员获取后端应用日志",
                "parameters": [
                    {
                        "type": "string",
                        "description": "日期，格式 YYYY-MM-DD",
                        "name": "date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最大返回条数，最多 500",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "日志级别，例如 INFO、WARN、ERROR",
                        "name": "level",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.OpsTextLogResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/admin/ops/error-logs": {
            "get": {
                "description": "只读读取配置指定的 Nginx error log。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AdminOps"
                ],
                "summary": "管理员获取 Nginx 错误日志",
                "parameters": [
                    {
                        "type": "string",
                        "description": "日期，格式 YYYY-MM-DD",
                        "name": "date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最大返回条数，最多 500",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.OpsTextLogResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/admin/ops/summary": {
            "get": {
                "description": "只读读取配置指定的 Nginx access log，统计指定日期的访问量。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AdminOps"
                ],
                "summary": "管理员获取运维流量概览",
                "parameters": [
                    {
                        "type": "string",
                        "description": "日期，格式 YYYY-MM-DD",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.OpsSummary"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/admin/recommendMenuItem": {
            "put": {
                "description": "设置或取消菜品今日推荐。设置为推荐时会自动取消其它菜品的今日推荐，保证最多只有一个今日推荐菜品。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "设置今日推荐菜品",
                "parameters": [
                    {
                        "description": "今日推荐参数",
                        "name": "recommend",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SetMenuRecommendationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"invalid params\",\"data\":\"Invalid menu ID\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "{\"code\":404,\"msg\":\"not found\",\"data\":\"Menu item not found\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"internal server error\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/admin/suggestion/list": {
            "post": {
                "description": "管理员查看用户建议，可按内容、联系方式、用户搜索。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Suggestion"
                ],
                "summary": "管理员获取建议列表",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AdminSuggestionListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Suggestion"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/admin/suggestion/status": {
            "put": {
                "description": "管理员将建议标记为未处理或已处理。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Suggestion"
                ],
                "summary": "管理员更新建议处理状态",
                "parameters": [
                    {
                        "description": "处理状态",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AdminSuggestionStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/admin/updateMenuItem": {
            "put": {
                "description": "根据菜品ID更新名称、简介、图片url、营养价值表和主要成分。图片url、营养价值表和主要成分可选，营养价值表和主要成分需要以JSON字符串格式提供。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "更新菜品",
                "parameters": [
                    {
                        "description": "菜品信息",
                        "name": "menu",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Menu"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{\"id\":1,\"name\":\"豆腐汤\",\"image_url\":\"/images/tofusoup.jpg\",\"desc\":\"清淡营养的素食汤品\",\"nutrition\":\"...\",\"ingredients\":\"...\",\"status\":1}}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"invalid params\",\"data\":\"Name and description are required\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "{\"code\":500,\"msg\":\"fail\",\"data\":\"Menu item not found\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"internal server error\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/admin/uploadMenuItem": {
            "post": {
                "description": "提供菜品的名称和简介，图片url、营养价值表、主要成分可选。营养价值表和主要成分需要以JSON字符串格式提供。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "上传菜品",
                "parameters": [
                    {
                        "description": "菜品信息",
                        "name": "menu",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Menu"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{\"id\":1,\"name\":\"豆腐汤\",\"image_url\":\"/images/tofusoup.jpg\",\"desc\":\"清淡营养的素食汤品，豆腐嫩滑，口感清香，富含植物蛋白\",\"nutrition\":\"...\",\"ingredients\":\"...\",\"status\":1}}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"invalid params\",\"data\":\"Name and description are required\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"internal server error\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/about/getActivityList": {
            "post": {
                "description": "获取净莲阁的活动列表，支持时间戳过滤和分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "About"
                ],
                "summary": "获取活动列表",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ActivityQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":[{\"id\":1,\"title\":\"素食文化活动\",\"content\":\"介绍素食文化\",\"img\":\"/images/activity1.jpg\",\"status\":1}]}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Activity"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"invalid params\",\"data\":\"Invalid input data\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"internal server error\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/about/getDescription": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "About"
                ],
                "summary": "获取净莲阁介绍",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/about/getTopImage": {
            "get": {
                "description": "获取净莲阁的头图。返回图片地址、简介、是否为头图等信息。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "About"
                ],
                "summary": "获取头图",
                "responses": {
                    "200": {
                        "description": "成功返回头图信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Image"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "简单的用户认证，基于微信小程序的用户ID，返回JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "用户认证",
                "parameters": [
                    {
                        "description": "认证参数",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{\"token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...\",\"user_id\":\"user123\"}}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"invalid params\",\"data\":\"Invalid input data\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"internal server error\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/donation/createDonation": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户支付成功后创建捐款记录（需要JWT认证）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Donation"
                ],
                "summary": "创建捐款记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "捐款信息",
                        "name": "donation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DonationCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":\"Donation created successfully\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"invalid params\",\"data\":\"Invalid input data\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "{\"code\":401,\"msg\":\"unauthorized\",\"data\":\"Token required\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"internal server error\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/donation/getDonationList": {
            "post": {
                "description": "获取捐款记录列表，支持年份、时间段、昵称筛选，支持按时间或金额排序，支持分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Donation"
                ],
                "summary": "获取功德榜列表",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DonationQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":[{\"id\":1,\"user_id\":\"user123\",\"donor_name\":\"善心人士\",\"amount\":100.00,\"donate_time\":\"2025-07-08T10:00:00Z\",\"is_visible\":1,\"message\":\"祝愿净莲阁越来越好\"}]}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Donation"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"invalid params\",\"data\":\"Invalid input data\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"internal server error\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/donation/getDonationStats": {
            "post": {
                "description": "获取指定时间段的捐款统计信息，包括总金额和总人次",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Donation"
                ],
                "summary": "获取捐款统计",
                "parameters": [
                    {
                        "description": "统计参数",
                        "name": "stats",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DonationStatsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{\"total_amount\":5000.00,\"total_count\":50}}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.DonationStats"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"invalid params\",\"data\":\"Invalid input data\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"internal server error\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/getImageList": {
            "post": {
                "description": "获取净莲阁的图片列表。返回图片地址、简介、是否为头图等信息。类型为 0 表示活动图片，1 表示餐厅介绍图片。top_pic 为 1 表示头图，0 表示非头图。",
                "produces": [
                    "application/json"
                ],
                "summary": "获取图片列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "图片类型：0 活动，1 餐厅介绍",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "是否为头图：0 否，1 是",
                        "name": "top_pic",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "页码, 从零开始",
                        "name": "pageNumber",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回图片列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Image"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/comment": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户对菜品进行评论（需要JWT认证）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "菜品评论",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "评论参数",
                        "name": "comment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.MenuCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":\"comment added successfully\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"invalid params\",\"data\":\"Invalid input data\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "{\"code\":401,\"msg\":\"unauthorized\",\"data\":\"Token required\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "{\"code\":404,\"msg\":\"not found\",\"data\":\"Menu item not found\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"internal server error\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/comment/delete": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户只能删除自己的评论；删除评论不影响点赞状态。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "删除自己的菜品评论",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "删除参数",
                        "name": "delete",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DeleteCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":\"comment deleted successfully\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/getComments": {
            "post": {
                "description": "获取指定菜品的评论列表，支持分页；带用户 token 时当前用户评论优先展示。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "获取菜品评论列表",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.MenuCommentsQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":[{\"id\":1,\"menu_id\":1,\"user_id\":\"user123\",\"preference\":1,\"comment\":\"非常好吃！\",\"status\":1,\"is_mine\":true}]}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.MenuFeedback"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"invalid params\",\"data\":\"Invalid input data\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "{\"code\":404,\"msg\":\"not found\",\"data\":\"Menu item not found\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"internal server error\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/getLikeStatus": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取用户对特定菜品的点赞状态（需要JWT认证）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "获取菜品点赞状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "查询参数",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.MenuLikeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{\"liked\":true,\"preference\":1}}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"invalid params\",\"data\":\"Invalid input data\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "{\"code\":401,\"msg\":\"unauthorized\",\"data\":\"Token required\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "{\"code\":404,\"msg\":\"not found\",\"data\":\"Menu item not found\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"internal server error\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/getMenu": {
            "post": {
                "description": "获取全部净莲阁菜单，返回菜单项列表，每个菜单项包含名称、图片 url、营养价值表 json、点赞数等信息。输入名称过滤菜单项，支持模糊匹配。如果提供了JWT token，会返回用户的点赞状态。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "获取净莲阁的菜单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token (可选)",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "查询参数",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.MenuQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":[{\"id\":1,\"name\":\"紫菜汤\",\"image_url\":\"/images/menu.jpg\",\"desc\":\"美味的菜品\",\"nutrition\":\"...\",\"ingredients\":\"...\",\"status\":1,\"like_count\":5,\"liked\":true}]}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.MenuWithUserLikes"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"invalid params\",\"data\":\"Invalid input data\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"internal server error\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/getMenuByID": {
            "post": {
                "description": "根据菜品ID获取单个菜品的详细信息，包括点赞数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "获取单个菜品信息",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.MenuByIDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{\"id\":1,\"name\":\"紫菜汤\",\"image_url\":\"/images/menu.jpg\",\"desc\":\"美味的菜品\",\"nutrition\":\"...\",\"ingredients\":\"...\",\"status\":1,\"like_count\":5,\"create_time\":\"2012-1-1\",\"update_time\":\"2012-1-1\"}}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.MenuWithLikes"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"invalid params\",\"data\":\"Invalid input data\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "{\"code\":404,\"msg\":\"not found\",\"data\":\"Menu item not found\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"internal server error\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/like": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户为喜欢的菜品点赞或取消点赞（需要JWT认证）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "菜品点赞",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "点赞参数",
                        "name": "like",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.MenuLikeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":\"liked successfully\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"invalid params\",\"data\":\"Invalid input data\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "{\"code\":401,\"msg\":\"unauthorized\",\"data\":\"Token required\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "{\"code\":404,\"msg\":\"not found\",\"data\":\"Menu item not found\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"internal server error\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/suggestion/create": {
            "post": {
                "description": "用户提交对餐厅、菜单或小程序的建议，联系方式可选。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Suggestion"
                ],
                "summary": "提交建议箱内容",
                "parameters": [
                    {
                        "description": "建议内容",
                        "name": "suggestion",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SuggestionCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":\"suggestion submitted successfully\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"invalid params\",\"data\":\"Suggestion content is required\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"internal server error\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/uploadImage": {
            "post": {
                "description": "上传净莲阁的图片。支持图片格式检查和大小限制，返回图片的访问地址、保存路径和文件名。",
                "produces": [
                    "application/json"
                ],
                "summary": "上传图片",
                "parameters": [
                    {
                        "type": "file",
                        "description": "图片文件",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "图片描述",
                        "name": "desc",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "是否为头图：0 否，1 是",
                        "name": "top_pic",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "图片类型：0 活动，1 餐厅介绍",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "model.Activity": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "create_time": {
                    "description": "Creation time",
                    "type": "string"
                },
                "event_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "img": {
                    "description": "Image address",
                    "type": "string"
                },
                "is_top": {
                    "type": "integer"
                },
                "place": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "update_time": {
                    "description": "Update time",
                    "type": "string"
                }
            }
        },
        "model.ActivityQueryRequest": {
            "type": "object",
            "properties": {
                "page_number": {
                    "description": "页码，从零开始",
                    "type": "integer",
                    "example": 0
                },
                "timestamp": {
                    "description": "时间戳",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "model.AdminCommentItem": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "create_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "menu_id": {
                    "type": "integer"
                },
                "menu_name": {
                    "type": "string"
                },
                "preference": {
                    "type": "integer"
                },
                "update_time": {
                    "type": "string"
                },
                "user_avatar_url": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "user_nickname": {
                    "type": "string"
                }
            }
        },
        "model.AdminCommentListRequest": {
            "type": "object",
            "properties": {
                "keyword": {
                    "description": "评论、用户 ID、菜品名称或 ID",
                    "type": "string",
                    "example": "好吃"
                },
                "page_number": {
                    "description": "页码，从零开始",
                    "type": "integer",
                    "example": 0
                },
                "page_size": {
                    "description": "每页数量",
                    "type": "integer",
                    "example": 20
                }
            }
        },
        "model.AdminLoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "\u003cadmin-password\u003e"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "model.AdminMenuListRequest": {
            "type": "object",
            "properties": {
                "archive_status": {
                    "description": "all, active, archived",
                    "type": "string",
                    "example": "all"
                },
                "keyword": {
                    "description": "菜单名称、介绍或 ID",
                    "type": "string",
                    "example": "紫菜汤"
                },
                "page_number": {
                    "description": "页码，从零开始",
                    "type": "integer",
                    "example": 0
                },
                "page_size": {
                    "description": "每页数量",
                    "type": "integer",
                    "example": 20
                }
            }
        },
        "model.AdminSuggestionListRequest": {
            "type": "object",
            "properties": {
                "handle_status": {
                    "description": "all, pending, handled",
                    "type": "string",
                    "example": "all"
                },
                "keyword": {
                    "type": "string",
                    "example": "清淡"
                },
                "page_number": {
                    "type": "integer",
                    "example": 0
                },
                "page_size": {
                    "type": "integer",
                    "example": 20
                }
            }
        },
        "model.AdminSuggestionStatusRequest": {
            "type": "object",
            "properties": {
                "handle_status": {
                    "description": "0 未处理，1 已处理",
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.ArchiveMenuRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "菜品ID",
                    "type": "integer",
                    "example": 1
                },
                "is_archived": {
                    "description": "是否下架：0 上架，1 下架",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.AuthRequest": {
            "type": "object",
            "properties": {
                "user_id": {
                    "description": "用户ID（来自微信小程序）",
                    "type": "string",
                    "example": "user123"
                }
            }
        },
        "model.DeleteCommentRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "评论反馈 ID",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.DeleteMenuRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "菜品ID",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.Donation": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "捐款金额（必填）",
                    "type": "number",
                    "example": 100
                },
                "create_time": {
                    "type": "string",
                    "example": "2025-07-08T10:00:00Z"
                },
                "donate_time": {
                    "description": "捐款时间（必填）",
                    "type": "string",
                    "example": "2025-07-08T10:00:00Z"
                },
                "donor_name": {
                    "description": "捐款人昵称（必填）",
                    "type": "string",
                    "example": "善心人士"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_visible": {
                    "description": "是否显示在榜单：0隐藏，1显示",
                    "type": "integer",
                    "example": 1
                },
                "message": {
                    "description": "留言",
                    "type": "string",
                    "example": "祝愿净莲阁越来越好"
                },
                "remarks": {
                    "description": "备注",
                    "type": "string",
                    "example": ""
                },
                "update_time": {
                    "type": "string",
                    "example": "2025-07-08T10:00:00Z"
                },
                "user_id": {
                    "description": "用户ID（必填）",
                    "type": "string",
                    "example": "user123"
                }
            }
        },
        "model.DonationCreateRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "捐款金额",
                    "type": "number",
                    "example": 100
                },
                "donor_name": {
                    "description": "捐款人昵称",
                    "type": "string",
                    "example": "善心人士"
                },
                "message": {
                    "description": "留言",
                    "type": "string",
                    "example": "祝愿净莲阁越来越好"
                }
            }
        },
        "model.DonationQueryRequest": {
            "type": "object",
            "properties": {
                "donor_name": {
                    "description": "捐款人昵称搜索（模糊匹配）",
                    "type": "string",
                    "example": "善心"
                },
                "page_number": {
                    "description": "页码，从零开始",
                    "type": "integer",
                    "example": 0
                },
                "page_size": {
                    "description": "每页数量",
                    "type": "integer",
                    "example": 10
                },
                "period": {
                    "description": "时间范围：all全年，first上半年，second下半年",
                    "type": "string",
                    "example": "all"
                },
                "sort_by": {
                    "description": "排序方式：time时间，amount金额",
                    "type": "string",
                    "example": "time"
                },
                "sort_order": {
                    "description": "排序顺序：desc降序，asc升序",
                    "type": "string",
                    "example": "desc"
                },
                "year": {
                    "description": "年份，0表示不限制",
                    "type": "integer",
                    "example": 2025
                }
            }
        },
        "model.DonationStats": {
            "type": "object",
            "properties": {
                "total_amount": {
                    "description": "总捐款金额",
                    "type": "number",
                    "example": 5000
                },
                "total_count": {
                    "description": "总捐款人次",
                    "type": "integer",
                    "example": 50
                }
            }
        },
        "model.DonationStatsRequest": {
            "type": "object",
            "properties": {
                "period": {
                    "description": "时间范围：all全年，first上半年，second下半年",
                    "type": "string",
                    "example": "all"
                },
                "year": {
                    "description": "年份，0表示不限制",
                    "type": "integer",
                    "example": 2025
                }
            }
        },
        "model.Image": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "/images/example.jpg"
                },
                "create_time": {
                    "description": "Creation time",
                    "type": "string"
                },
                "desc": {
                    "type": "string",
                    "example": "A beautiful image"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "status": {
                    "description": "Status: 0 deleted, 1 normal",
                    "type": "integer",
                    "example": 1
                },
                "top_pic": {
                    "description": "Whether it is a top image",
                    "type": "integer",
                    "example": 1
                },
                "type": {
                    "description": "Image type: 0 activity, 1 restaurant introduction",
                    "type": "integer",
                    "example": 0
                },
                "update_time": {
                    "description": "Update time",
                    "type": "string"
                }
            }
        },
        "model.Menu": {
            "type": "object",
            "properties": {
                "archive_time": {
                    "description": "下架时间",
                    "type": "string",
                    "example": "2012-1-1"
                },
                "create_time": {
                    "description": "Creation time",
                    "type": "string",
                    "example": "2012-1-1"
                },
                "desc": {
                    "type": "string",
                    "example": "美味的菜品"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "image_url": {
                    "type": "string",
                    "example": "/images/menu.jpg"
                },
                "ingredients": {
                    "type": "string",
                    "example": "{\"米\", \"豆腐\"}"
                },
                "is_archived": {
                    "description": "是否下架：0 上架，1 下架",
                    "type": "integer",
                    "example": 0
                },
                "is_recommended": {
                    "description": "是否今日推荐：0 否，1 是",
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "description": "菜品名称",
                    "type": "string",
                    "example": "紫菜汤"
                },
                "nutrition": {
                    "type": "string",
                    "example": "{\"protein\": \"10g\", \"carbs\": \"20g\", \"fat\": \"5g\"}"
                },
                "status": {
                    "description": "状态：0 删除，1 正常",
                    "type": "integer",
                    "example": 1
                },
                "update_time": {
                    "description": "Update time",
                    "type": "string",
                    "example": "2012-1-1"
                }
            }
        },
        "model.MenuByIDRequest": {
            "type": "object",
            "properties": {
                "menu_id": {
                    "description": "菜品ID",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.MenuCommentRequest": {
            "type": "object",
            "properties": {
                "comment": {
                    "description": "评论内容",
                    "type": "string",
                    "example": "非常好吃的菜品！"
                },
                "menu_id": {
                    "description": "菜品ID",
                    "type": "integer",
                    "example": 1
                },
                "user_avatar_url": {
                    "type": "string",
                    "example": "/uploads/images/avatar.jpg"
                },
                "user_nickname": {
                    "description": "评论展示昵称",
                    "type": "string",
                    "example": "莲友"
                }
            }
        },
        "model.MenuCommentsQueryRequest": {
            "type": "object",
            "properties": {
                "menu_id": {
                    "description": "菜品ID",
                    "type": "integer",
                    "example": 1
                },
                "page_number": {
                    "description": "页码，从零开始",
                    "type": "integer",
                    "example": 0
                },
                "page_size": {
                    "description": "每页数量",
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "model.MenuFeedback": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string",
                    "example": "非常好吃"
                },
                "create_time": {
                    "description": "Creation time",
                    "type": "string",
                    "example": "2012-1-1"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_mine": {
                    "type": "boolean",
                    "example": true
                },
                "menu_id": {
                    "description": "菜单 ID",
                    "type": "integer",
                    "example": 1
                },
                "preference": {
                    "description": "状态：0 默认，1 喜欢，2 不喜欢",
                    "type": "integer",
                    "example": 1
                },
                "status": {
                    "description": "状态：0 删除，1 正常",
                    "type": "integer",
                    "example": 1
                },
                "update_time": {
                    "description": "Update time",
                    "type": "string",
                    "example": "2012-1-1"
                },
                "user_avatar_url": {
                    "type": "string",
                    "example": "/uploads/images/avatar.jpg"
                },
                "user_id": {
                    "description": "用户 ID",
                    "type": "string",
                    "example": "user123"
                },
                "user_nickname": {
                    "type": "string",
                    "example": "莲友"
                }
            }
        },
        "model.MenuLikeRequest": {
            "type": "object",
            "properties": {
                "menu_id": {
                    "description": "菜品ID",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.MenuQueryRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "菜单名称，支持模糊匹配",
                    "type": "string",
                    "example": "紫菜汤"
                },
                "page_number": {
                    "description": "页码，从零开始",
                    "type": "integer",
                    "example": 0
                },
                "page_size": {
                    "description": "每页数量",
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "model.MenuWithLikes": {
            "type": "object",
            "properties": {
                "archive_time": {
                    "description": "下架时间",
                    "type": "string",
                    "example": "2012-1-1"
                },
                "create_time": {
                    "description": "Creation time",
                    "type": "string",
                    "example": "2012-1-1"
                },
                "desc": {
                    "type": "string",
                    "example": "美味的菜品"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "image_url": {
                    "type": "string",
                    "example": "/images/menu.jpg"
                },
                "ingredients": {
                    "type": "string",
                    "example": "{\"米\", \"豆腐\"}"
                },
                "is_archived": {
                    "description": "是否下架：0 上架，1 下架",
                    "type": "integer",
                    "example": 0
                },
                "is_recommended": {
                    "description": "是否今日推荐：0 否，1 是",
                    "type": "integer",
                    "example": 1
                },
                "like_count": {
                    "description": "点赞数",
                    "type": "integer",
                    "example": 5
                },
                "name": {
                    "description": "菜品名称",
                    "type": "string",
                    "example": "紫菜汤"
                },
                "nutrition": {
                    "type": "string",
                    "example": "{\"protein\": \"10g\", \"carbs\": \"20g\", \"fat\": \"5g\"}"
                },
                "status": {
                    "description": "状态：0 删除，1 正常",
                    "type": "integer",
                    "example": 1
                },
                "update_time": {
                    "description": "Update time",
                    "type": "string",
                    "example": "2012-1-1"
                }
            }
        },
        "model.MenuWithUserLikes": {
            "type": "object",
            "properties": {
                "archive_time": {
                    "description": "下架时间",
                    "type": "string",
                    "example": "2012-1-1"
                },
                "create_time": {
                    "description": "Creation time",
                    "type": "string",
                    "example": "2012-1-1"
                },
                "desc": {
                    "type": "string",
                    "example": "美味的菜品"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "image_url": {
                    "type": "string",
                    "example": "/images/menu.jpg"
                },
                "ingredients": {
                    "type": "string",
                    "example": "{\"米\", \"豆腐\"}"
                },
                "is_archived": {
                    "description": "是否下架：0 上架，1 下架",
                    "type": "integer",
                    "example": 0
                },
                "is_recommended": {
                    "description": "是否今日推荐：0 否，1 是",
                    "type": "integer",
                    "example": 1
                },
                "like_count": {
                    "description": "点赞数",
                    "type": "integer",
                    "example": 5
                },
                "liked": {
                    "description": "当前用户是否已点赞",
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "description": "菜品名称",
                    "type": "string",
                    "example": "紫菜汤"
                },
                "nutrition": {
                    "type": "string",
                    "example": "{\"protein\": \"10g\", \"carbs\": \"20g\", \"fat\": \"5g\"}"
                },
                "status": {
                    "description": "状态：0 删除，1 正常",
                    "type": "integer",
                    "example": 1
                },
                "update_time": {
                    "description": "Update time",
                    "type": "string",
                    "example": "2012-1-1"
                }
            }
        },
        "model.OpsAccessLogItem": {
            "type": "object",
            "properties": {
                "bytes": {
                    "type": "integer"
                },
                "ip": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "raw": {
                    "type": "string"
                },
                "referer": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                },
                "user_agent": {
                    "type": "string"
                }
            }
        },
        "model.OpsAccessLogResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.OpsAccessLogItem"
                    }
                },
                "source_exists": {
                    "type": "boolean"
                }
            }
        },
        "model.OpsPathStat": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "model.OpsStatusStat": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "model.OpsSummary": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "source_exists": {
                    "type": "boolean"
                },
                "status_4xx": {
                    "type": "integer"
                },
                "status_5xx": {
                    "type": "integer"
                },
                "status_counts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.OpsStatusStat"
                    }
                },
                "top_paths": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.OpsPathStat"
                    }
                },
                "total_bytes": {
                    "type": "integer"
                },
                "total_requests": {
                    "type": "integer"
                },
                "unique_ips": {
                    "type": "integer"
                }
            }
        },
        "model.OpsTextLogItem": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "string"
                },
                "raw": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "model.OpsTextLogResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.OpsTextLogItem"
                    }
                },
                "source_exists": {
                    "type": "boolean"
                }
            }
        },
        "model.SetMenuRecommendationRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "菜品ID",
                    "type": "integer",
                    "example": 1
                },
                "is_recommended": {
                    "description": "是否设为今日推荐：0 否，1 是",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.Suggestion": {
            "type": "object",
            "properties": {
                "contact": {
                    "type": "string",
                    "example": "微信或手机号"
                },
                "content": {
                    "type": "string",
                    "example": "希望增加更多清淡菜品"
                },
                "create_time": {
                    "description": "Creation time",
                    "type": "string"
                },
                "handle_status": {
                    "description": "处理状态：0 未处理，1 已处理",
                    "type": "integer",
                    "example": 0
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "status": {
                    "description": "记录状态：0 删除，1 正常",
                    "type": "integer",
                    "example": 1
                },
                "update_time": {
                    "description": "Update time",
                    "type": "string"
                },
                "user_avatar_url": {
                    "type": "string",
                    "example": "/uploads/images/avatar.jpg"
                },
                "user_id": {
                    "type": "string",
                    "example": "user123"
                },
                "user_nickname": {
                    "type": "string",
                    "example": "莲友"
                }
            }
        },
        "model.SuggestionCreateRequest": {
            "type": "object",
            "properties": {
                "contact": {
                    "type": "string",
                    "example": "微信或手机号"
                },
                "content": {
                    "type": "string",
                    "example": "希望增加更多清淡菜品"
                },
                "user_avatar_url": {
                    "type": "string",
                    "example": "/uploads/images/avatar.jpg"
                },
                "user_nickname": {
                    "type": "string",
                    "example": "莲友"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "49.234.22.169:8000",
	BasePath:         "",
	Schemes:          []string{"http"},
	Title:            "Jingliange Server API",
	Description:      "This is the backend API for Jingliange.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
