// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "TO IMPLEMENT",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/deleteMenuItem": {
            "delete": {
                "description": "根据菜品ID删除菜品（软删除，将状态标记为0）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "删除菜品",
                "parameters": [
                    {
                        "description": "删除参数",
                        "name": "delete",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DeleteMenuRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"invalid params\",\"data\":\"Invalid menu ID\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "{\"code\":404,\"msg\":\"not found\",\"data\":\"Menu item not found\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"internal server error\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/admin/uploadMenuItem": {
            "post": {
                "description": "提供菜品的名称、图片url、简介、营养价值表、主要成分，上传到数据库。营养价值表和主要成分需要以JSON字符串格式提供。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "上传菜品",
                "parameters": [
                    {
                        "description": "菜品信息",
                        "name": "menu",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Menu"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{\"id\":1,\"name\":\"豆腐汤\",\"image_url\":\"/images/tofusoup.jpg\",\"desc\":\"清淡营养的素食汤品，豆腐嫩滑，口感清香，富含植物蛋白\",\"nutrition\":\"...\",\"ingredients\":\"...\",\"status\":1}}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"invalid params\",\"data\":\"All fields are required\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"internal server error\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/about/getActivityList": {
            "post": {
                "description": "获取净莲阁的活动列表，支持时间戳过滤和分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "About"
                ],
                "summary": "获取活动列表",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ActivityQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":[{\"id\":1,\"title\":\"素食文化活动\",\"content\":\"介绍素食文化\",\"img\":\"/images/activity1.jpg\",\"status\":1}]}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Activity"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"invalid params\",\"data\":\"Invalid input data\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"internal server error\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/about/getDescription": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "About"
                ],
                "summary": "获取净莲阁介绍",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/about/getTopImage": {
            "get": {
                "description": "获取净莲阁的头图。返回图片地址、简介、是否为头图等信息。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "About"
                ],
                "summary": "获取头图",
                "responses": {
                    "200": {
                        "description": "成功返回头图信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Image"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/getImageList": {
            "post": {
                "description": "获取净莲阁的图片列表。返回图片地址、简介、是否为头图等信息。类型为 0 表示活动图片，1 表示餐厅介绍图片。top_pic 为 1 表示头图，0 表示非头图。",
                "produces": [
                    "application/json"
                ],
                "summary": "获取图片列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "图片类型：0 活动，1 餐厅介绍",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "是否为头图：0 否，1 是",
                        "name": "top_pic",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "页码, 从零开始",
                        "name": "pageNumber",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回图片列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Image"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/getMenu": {
            "post": {
                "description": "获取全部净莲阁菜单，返回菜单项列表，每个菜单项包含名称、图片 url、营养价值表 json等信息。输入名称过滤菜单项，支持模糊匹配。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "获取净莲阁的菜单",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.MenuQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":[{\"id\":1,\"name\":\"紫菜汤\",\"image_url\":\"/images/menu.jpg\",\"desc\":\"美味的菜品\",\"nutrition\":\"...\",\"ingredients\":\"...\",\"status\":1}]}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Menu"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"invalid params\",\"data\":\"Invalid input data\"}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"internal server error\",\"data\":null}",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/uploadImage": {
            "post": {
                "description": "上传净莲阁的图片。支持图片格式检查和大小限制，返回图片的访问地址、保存路径和文件名。",
                "produces": [
                    "application/json"
                ],
                "summary": "上传图片",
                "parameters": [
                    {
                        "type": "file",
                        "description": "图片文件",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "图片描述",
                        "name": "desc",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "是否为头图：0 否，1 是",
                        "name": "top_pic",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "图片类型：0 活动，1 餐厅介绍",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/app.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "model.Activity": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createTime": {
                    "description": "Creation time",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "img": {
                    "description": "Image address",
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updateTime": {
                    "description": "Update time",
                    "type": "string"
                }
            }
        },
        "model.ActivityQueryRequest": {
            "type": "object",
            "properties": {
                "pageNumber": {
                    "description": "页码，从零开始",
                    "type": "integer",
                    "example": 0
                },
                "timestamp": {
                    "description": "时间戳",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "model.DeleteMenuRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "菜品ID",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.Image": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "/images/example.jpg"
                },
                "createTime": {
                    "description": "Creation time",
                    "type": "string"
                },
                "desc": {
                    "type": "string",
                    "example": "A beautiful image"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "status": {
                    "description": "Status: 0 deleted, 1 normal",
                    "type": "integer",
                    "example": 1
                },
                "top_pic": {
                    "description": "Whether it is a top image",
                    "type": "integer",
                    "example": 1
                },
                "type": {
                    "description": "Image type: 0 activity, 1 restaurant introduction",
                    "type": "integer",
                    "example": 0
                },
                "updateTime": {
                    "description": "Update time",
                    "type": "string"
                }
            }
        },
        "model.Menu": {
            "type": "object",
            "properties": {
                "createTime": {
                    "description": "Creation time",
                    "type": "string",
                    "example": "2012-1-1"
                },
                "desc": {
                    "type": "string",
                    "example": "美味的菜品"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "image_url": {
                    "type": "string",
                    "example": "/images/menu.jpg"
                },
                "ingredients": {
                    "type": "string",
                    "example": "{\"米\", \"豆腐\"}"
                },
                "name": {
                    "description": "菜品名称",
                    "type": "string",
                    "example": "紫菜汤"
                },
                "nutrition": {
                    "type": "string",
                    "example": "{\"protein\": \"10g\", \"carbs\": \"20g\", \"fat\": \"5g\"}"
                },
                "status": {
                    "description": "状态：0 删除，1 正常",
                    "type": "integer",
                    "example": 1
                },
                "updateTime": {
                    "description": "Update time",
                    "type": "string",
                    "example": "2012-1-1"
                }
            }
        },
        "model.MenuQueryRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "菜单名称，支持模糊匹配",
                    "type": "string",
                    "example": "紫菜汤"
                },
                "pageNumber": {
                    "description": "页码，从零开始",
                    "type": "integer",
                    "example": 0
                },
                "pageSize": {
                    "description": "每页数量",
                    "type": "integer",
                    "example": 10
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "https://jingliange.com",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Jingliange Server API",
	Description:      "This is the backend API for Jingliange.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
